CREATE DATABASE DogWalkingBusinessDb;
GO

USE DogWalkingBusinessDb;
GO

CREATE TABLE Clients (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    PhoneNumber NVARCHAR(20) NOT NULL
);

CREATE TABLE Dogs (
    Id INT PRIMARY KEY IDENTITY,
    ClientId INT FOREIGN KEY REFERENCES Clients(Id),
    Name NVARCHAR(100) NOT NULL,
    Breed NVARCHAR(100) NOT NULL,
    Age INT NOT NULL
);

CREATE TABLE Walks (
    Id INT PRIMARY KEY IDENTITY,
    DogId INT FOREIGN KEY REFERENCES Dogs(Id),
    WalkDate DATETIME NOT NULL,
    Duration TIME NOT NULL
);

CREATE TABLE Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL
);